# Generated by AICR v1.0.0 — do not edit.
#
# One module call per component. depends_on carries the recipe's graph exactly:
# a component waits for its declared dependencies and nothing else, so
# independent components apply concurrently. A component's own pre / post /
# readiness folders chain inside the module, which is why depending on the
# module means the component is done.

# 002-agentgateway — agentgateway v1.5.0
# plus 001-agentgateway-pre, 003-agentgateway-post, 004-agentgateway-readiness
module "agentgateway" {
  source = "./modules/component"

  release_name     = "agentgateway"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/002-agentgateway/values.yaml",
  ]

  pre_chart       = "${path.module}/001-agentgateway-pre"
  post_chart      = "${path.module}/003-agentgateway-post"
  readiness_chart = "${path.module}/004-agentgateway-readiness"

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 005-nvsentinel — nvsentinel v0.3.0
module "nvsentinel" {
  source = "./modules/component"

  release_name     = "nvsentinel"
  namespace        = "nvsentinel"
  create_namespace = true

  chart         = "nvsentinel"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v0.3.0"

  values_files = [
    "${path.module}/005-nvsentinel/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.agentgateway,
  ]
}
