# Generated by AICR v1.0.0 — do not edit.

output "criteria" {
  description = "The AICR criteria this bundle was resolved from."
  value       = ""
}

output "components" {
  description = "Component -> namespace, for every component in the recipe."
  value = {
    "agentgateway" = "agentgateway-system"
    "nvsentinel"   = "nvsentinel"
  }
}

output "releases" {
  description = "Helm release -> namespace, auxiliary pre/post/readiness releases included."
  value = {
    "agentgateway-pre"       = "agentgateway-system"
    "agentgateway"           = "agentgateway-system"
    "agentgateway-post"      = "agentgateway-system"
    "agentgateway-readiness" = "agentgateway-system"
    "nvsentinel"             = "nvsentinel"
  }
}

output "namespaces" {
  description = "Distinct namespaces the bundle installs into."
  value       = distinct(["agentgateway-system", "nvsentinel"])
}
