# Generated by AICR v1.0.0 — do not edit.
#
# One module call per release. depends_on carries the recipe's dependency
# graph exactly: a component waits for its declared dependencies and nothing
# else, so independent components apply concurrently.

# 001-gpu-operator — gpu-operator v25.3.3
module "gpu_operator" {
  source = "./modules/component"

  release_name     = "gpu-operator"
  namespace        = "gpu-operator"
  create_namespace = true

  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v25.3.3"

  values_files = [
    "${path.module}/001-gpu-operator/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 002-kai-scheduler — kai-scheduler v0.16.9
module "kai_scheduler" {
  source = "./modules/component"

  release_name     = "kai-scheduler"
  namespace        = "kai-scheduler"
  create_namespace = true

  chart         = "kai-scheduler"
  repository    = "oci://ghcr.io/kai-scheduler/kai-scheduler"
  chart_version = "v0.16.9"

  values_files = [
    "${path.module}/002-kai-scheduler/values.yaml",
  ]

  # Asynchronous: helm --wait times out on this component's custom-resource
  # readiness even though its pods start. Ordering still holds; readiness does not.
  atomic  = var.atomic
  wait    = false
  timeout = 1200

  depends_on = [
    module.gpu_operator,
  ]
}
