# Generated by AICR v1.0.0 — do not edit.
#
# One module call per release. depends_on carries the recipe's dependency
# graph exactly: a component waits for its declared dependencies and nothing
# else, so independent components apply concurrently.

# 001-cert-manager — cert-manager v1.17.2
module "cert_manager" {
  source = "./modules/component"

  release_name     = "cert-manager"
  namespace        = "cert-manager"
  create_namespace = true

  chart         = "cert-manager"
  repository    = "https://charts.jetstack.io"
  chart_version = "v1.17.2"

  values_files = [
    "${path.module}/001-cert-manager/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 002-nfd — node-feature-discovery 0.18.1
module "nfd" {
  source = "./modules/component"

  release_name     = "nfd"
  namespace        = "node-feature-discovery"
  create_namespace = true

  chart         = "node-feature-discovery"
  repository    = "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart_version = "0.18.1"

  values_files = [
    "${path.module}/002-nfd/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 003-gpu-operator — gpu-operator v25.3.3
module "gpu_operator" {
  source = "./modules/component"

  release_name     = "gpu-operator"
  namespace        = "gpu-operator"
  create_namespace = true

  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v25.3.3"

  values_files = [
    "${path.module}/003-gpu-operator/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.cert_manager,
    module.nfd,
  ]
}
