# Generated by AICR v1.0.0 — do not edit.

output "criteria" {
  description = "The AICR criteria this bundle was resolved from."
  value       = ""
}

output "releases" {
  description = "Release name -> namespace, for every release in the bundle."
  value = {
    "cert-manager" = "cert-manager"
    "nfd"          = "node-feature-discovery"
    "gpu-operator" = "gpu-operator"
  }
}

output "namespaces" {
  description = "Distinct namespaces the bundle installs into."
  value       = distinct(["cert-manager", "node-feature-discovery", "gpu-operator"])
}
