# Generated by AICR v1.0.0 — do not edit.

variable "kubeconfig_path" {
  description = "Path to a kubeconfig file. Used only when cluster_host is null."
  type        = string
  default     = "~/.kube/config"
}

variable "kube_context" {
  description = "Context within kubeconfig_path. Used only when cluster_host is null."
  type        = string
  default     = null
}

variable "cluster_host" {
  description = <<-EOT
    Kubernetes API server URL. Set this (with the matching credentials below)
    to bind the bundle to a cluster declared in the same configuration instead
    of a kubeconfig on disk.
  EOT
  type        = string
  default     = null
}

variable "cluster_ca_certificate" {
  description = "PEM-encoded CA bundle for cluster_host."
  type        = string
  default     = null
}

variable "cluster_client_certificate" {
  description = "PEM-encoded client certificate for cluster_host."
  type        = string
  default     = null
  sensitive   = true
}

variable "cluster_client_key" {
  description = "PEM-encoded client key for cluster_host."
  type        = string
  default     = null
  sensitive   = true
}

variable "cluster_token" {
  description = "Bearer token for cluster_host, as an alternative to a client certificate."
  type        = string
  default     = null
  sensitive   = true
}

variable "wait" {
  description = <<-EOT
    Wait for each release's workloads to become ready before the resource is
    considered applied. This is what makes depends_on mean "the dependency is
    running", not merely "its manifests were submitted" — leave it on unless a
    component in this recipe is known to never converge (see README.md).
  EOT
  type        = bool
  default     = true
}

variable "timeout" {
  description = <<-EOT
    Per-release wait timeout, in seconds. Generous on purpose: several
    components in a datacenter recipe pull large images before any workload
    reports ready, and a short timeout turns a slow install into a confusing
    failure. A genuine hang is only delayed by this, not hidden.
  EOT
  type        = number
  default     = 900
}

variable "atomic" {
  description = "Roll a release back if it fails to install. Off by default: a failed release left in place is easier to diagnose."
  type        = bool
  default     = false
}
