# Generated by AICR v1.0.0 — do not edit.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
  }
}

# The bundle does not create a cluster. Point it at one of two ways:
#
#   * leave var.cluster_host unset and the provider reads var.kubeconfig_path
#     (the default, ~/.kube/config) with var.kube_context;
#   * regenerate with --terraform-child-module and call this directory from a
#     configuration that declares the cluster and configures the provider.
#     A module carrying its own provider block cannot take depends_on,
#     count or for_each, and some engines refuse to walk one at all — so
#     composing is a different shape, not a different argument.
provider "helm" {
  kubernetes = {
    config_path    = var.cluster_host == null ? var.kubeconfig_path : null
    config_context = var.cluster_host == null ? var.kube_context : null

    host                   = var.cluster_host
    cluster_ca_certificate = var.cluster_ca_certificate
    client_certificate     = var.cluster_client_certificate
    client_key             = var.cluster_client_key
    token                  = var.cluster_token
  }
}
