# Generated by AICR v1.0.0 — do not edit.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

# The bundle does not create a cluster. Point it at one of two ways:
#
#   * leave var.cluster_host unset and the provider reads var.kubeconfig_path
#     (the default, ~/.kube/config) with var.kube_context;
#   * set var.cluster_host and friends from a cluster resource declared in the
#     configuration that consumes this bundle. Those attributes are unknown
#     until the cluster is created, which makes every release in the bundle
#     unplannable on the first pass. An engine with deferred actions converges
#     that in two rounds; stock `terraform apply` needs the cluster first.
provider "helm" {
  kubernetes = {
    config_path    = var.cluster_host == null ? var.kubeconfig_path : null
    config_context = var.cluster_host == null ? var.kube_context : null

    host                   = var.cluster_host
    cluster_ca_certificate = var.cluster_ca_certificate
    client_certificate     = var.cluster_client_certificate
    client_key             = var.cluster_client_key
    token                  = var.cluster_token
  }
}
