# Generated by AICR v1.0.0 — do not edit.
#
# One module call per component. depends_on carries the recipe's graph exactly:
# a component waits for its declared dependencies and nothing else, so
# independent components apply concurrently. A component's own pre / post /
# readiness folders chain inside the module, which is why depending on the
# module means the component is done.

# 001-agentgateway-crds — agentgateway-crds v1.5.0
# plus 002-agentgateway-crds-post
module "agentgateway_crds" {
  source = "./modules/component"

  release_name     = "agentgateway-crds"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway-crds"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/001-agentgateway-crds/values.yaml",
  ]

  post_chart = "${path.module}/002-agentgateway-crds-post"

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 003-agentgateway — agentgateway v1.5.0
module "agentgateway" {
  source = "./modules/component"

  release_name     = "agentgateway"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/003-agentgateway/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.agentgateway_crds,
  ]
}
