# Generated by AICR v1.0.0 — do not edit.
#
# One module call per release. depends_on carries the recipe's dependency
# graph exactly: a component waits for its declared dependencies and nothing
# else, so independent components apply concurrently.

# 001-agentgateway-crds — agentgateway-crds v1.5.0
module "agentgateway_crds" {
  source = "./modules/component"

  release_name     = "agentgateway-crds"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway-crds"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/001-agentgateway-crds/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 002-agentgateway-crds-post — chart bundled in this directory
module "agentgateway_crds_post" {
  source = "./modules/component"

  release_name     = "agentgateway-crds-post"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart = "${path.module}/002-agentgateway-crds-post"

  values_files = [
    "${path.module}/002-agentgateway-crds-post/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.agentgateway_crds,
  ]
}

# 003-agentgateway — agentgateway v1.5.0
module "agentgateway" {
  source = "./modules/component"

  release_name     = "agentgateway"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/003-agentgateway/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.agentgateway_crds_post,
  ]
}
