#!/usr/bin/env bash
# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# AICR Deployment Script
# Generated by AICR Bundler v1.0.0
#
# Usage: ./deploy.sh [--no-wait] [--best-effort] [--retries N]
#   --no-wait      Skip Helm chart-level wait where AICR uses --wait (keeps --timeout for hooks)
#   --best-effort  Continue past individual component failures (log warnings)
#   --retries N    Retry failed helm/kubectl operations N times with backoff (default: 5, 0 = fail-fast)
#
# This script is optional — each component subdirectory has its own install.sh
# with a single baked-in `helm upgrade --install` command. For detailed behavior
# docs (CRD ordering, async components, error handling), see the AICR CLI Reference:
#   https://github.com/NVIDIA/aicr/blob/main/docs/user/cli-reference.md#deploy-script-behavior-deploysh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Run helm commands from a temp directory to prevent local chart directories
# (e.g., bundle/001-nodewright-operator/) from shadowing remote chart references.
HELM_WORKDIR="$(mktemp -d)"
trap 'rm -rf "${HELM_WORKDIR}"; exit 130' INT TERM
trap 'rm -rf "${HELM_WORKDIR}"' EXIT

HELM_TIMEOUT="10m"
NO_WAIT=false
BEST_EFFORT=false
FAILED_COMPONENTS=""
MAX_RETRIES=5

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-wait) NO_WAIT=true; shift ;;
    --best-effort) BEST_EFFORT=true; shift ;;
    --retries)
      if [[ $# -lt 2 ]]; then echo "Error: --retries requires a value"; exit 1; fi
      if ! [[ "$2" =~ ^[0-9]+$ ]]; then echo "Error: --retries requires a non-negative integer"; exit 1; fi
      MAX_RETRIES="$2"; shift 2 ;;
    *) echo "Error: unknown option: $1"; echo "Usage: ./deploy.sh [--no-wait] [--best-effort] [--retries N]"; exit 1 ;;
  esac
done
# ==============================================================================
# Output helpers (respects NO_COLOR and non-TTY)
# ==============================================================================
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  _G=$'\033[0;32m';_R=$'\033[0;31m';_Y=$'\033[1;33m'
  _B=$'\033[1m';_D=$'\033[2m';_X=$'\033[0m'
else
  _G='';_R='';_Y='';_B='';_D='';_X=''
fi

function _ok()       { printf '%s✓%s %s\n' "${_G}" "${_X}" "$*"; }
function _fail()     { printf '%s✗%s %s\n' "${_R}" "${_X}" "$*"; }
function _warn_line(){ printf '%s⚠%s %s\n' "${_Y}" "${_X}" "$*"; }

function _step_header() {
  local manual_dir
  printf -v manual_dir '%q' "$5"
  printf '\n%s┌─ [%s/%s] %s  →  %s%s\n' "${_B}" "$1" "$2" "$3" "$4" "${_X}"
  printf '%s│  Manual (approx, set KUBECONFIG_FLAG/DRY_RUN_FLAG/COMPONENT_WAIT_ARGS as needed): cd %s && bash install.sh%s\n' "${_D}" "${manual_dir}" "${_X}"
}

function _step_ok() {
  printf '%s└─ ✓%s %s installed\n' "${_G}" "${_X}" "$1"
}

function _step_fail() {
  printf '%s└─ ✗%s %s FAILED (after %s attempts)\n' "${_R}" "${_X}" "$1" "$2"
}

function _step_retry() {
  printf '%s  ↺%s %s: attempt %s/%s failed, retrying in %ss...\n' "${_Y}" "${_X}" "$1" "$2" "$3" "$4"
}

# Export env vars consumed by each folder's install.sh (rendered by localformat).
# DRY_RUN_FLAG / KUBECONFIG_FLAG / HELM_DEBUG_FLAG default to empty strings.
export DRY_RUN_FLAG="${DRY_RUN_FLAG:-}"
export KUBECONFIG_FLAG="${KUBECONFIG_FLAG:-}"
export HELM_DEBUG_FLAG="${HELM_DEBUG_FLAG:-}"

function helm_failed() {
  if [[ "${BEST_EFFORT}" == "true" ]]; then
    _warn_line "$1 install failed, continuing (--best-effort)"
    FAILED_COMPONENTS="${FAILED_COMPONENTS} $1"
  else
    exit 1
  fi
}

# Compute backoff delay from attempt number (1-indexed).
# Examples: attempt 1→5s, 2→20s, 3→45s, 4→80s, 5→120s (cap)
function backoff_seconds() {
  local attempt=$1
  local seconds=$(( attempt * attempt * 5 ))
  if [[ ${seconds} -gt 120 ]]; then seconds=120; fi
  echo "${seconds}"
}

# Clean up stale Helm hook Jobs before retrying. When a hook Job (e.g.,
# crd-upgrader) times out or fails, it stays in the namespace and blocks
# subsequent install attempts with "Job not ready" errors.
# Helm hooks are identified by the helm.sh/hook *annotation* (not a label),
# so we list all non-succeeded Jobs and check each individually via JSON.
function cleanup_helm_hooks() {
  local namespace="$1"
  local job_names
  job_names=$(kubectl get jobs -n "${namespace}" \
    --field-selector=status.successful=0 \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' \
    2>/dev/null || true)
  if [[ -z "${job_names}" ]]; then
    return
  fi
  while IFS= read -r name; do
    [[ -z "${name}" ]] && continue
    # Get the full Job JSON to reliably check annotations and status
    local job_json
    job_json=$(kubectl get job "${name}" -n "${namespace}" -o json 2>/dev/null || true)
    [[ -z "${job_json}" ]] && continue
    # Skip non-hook Jobs (no helm.sh/hook annotation)
    local hook_val
    hook_val=$(echo "${job_json}" | grep -o '"helm.sh/hook"' || true)
    [[ -z "${hook_val}" ]] && continue
    # Capture diagnostics before deleting. This helps diagnose transient hook
    # failures (e.g., dynamo ssh-keygen) that are otherwise lost after cleanup.
    echo "  --- Failed hook Job ${name} diagnostics ---"
    kubectl describe job "${name}" -n "${namespace}" 2>/dev/null | tail -50 || true
    local pod_names
    pod_names=$(kubectl get pods -n "${namespace}" -l "job-name=${name}" \
      -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null || true)
    for pod_name in ${pod_names}; do
      echo "  --- Hook pod ${pod_name} describe ---"
      kubectl describe pod "${pod_name}" -n "${namespace}" 2>/dev/null | tail -50 || true
    done
    echo "  --- End diagnostics for ${name} ---"
    # Delete any non-succeeded hook Job. This function only runs after a Helm
    # failure, so any hook Job without a successful completion is blocking the
    # retry — whether it failed, is stuck Pending (timed out before the pod
    # started), or is still active with a stuck container.
    echo "  Cleaning up stale Helm hook Job ${name} in ${namespace}..."
    kubectl delete job "${name}" -n "${namespace}" --ignore-not-found 2>/dev/null || true
  done <<< "${job_names}"
}

function dump_kai_scheduler_helm_diagnostics() {
  local namespace="$1"
  if [[ "${namespace}" != "kai-scheduler" ]]; then
    return
  fi

  echo "  --- ${namespace} diagnostics ---"
  echo "  Jobs:"
  kubectl get jobs -n "${namespace}" 2>/dev/null || true
  echo "  Job descriptions:"
  kubectl describe jobs -n "${namespace}" 2>/dev/null || true
  echo "  Pods:"
  kubectl get pods -n "${namespace}" -o wide 2>/dev/null || true
  echo "  Pod descriptions:"
  kubectl describe pods -n "${namespace}" 2>/dev/null || true
  echo "  Recent events:"
  kubectl get events -n "${namespace}" --sort-by='.lastTimestamp' 2>/dev/null | tail -30 || true
  echo "  --- End ${namespace} diagnostics ---"
}

# Components that use operator patterns with custom resources that reconcile
# asynchronously. Helm --wait may time out waiting for CR readiness even though
# all pods start successfully. These components are installed without --wait.
ASYNC_COMPONENTS="kai-scheduler"

# ==============================================================================
# Pre-flight checks
# ==============================================================================
# Verify the cluster is clean before deploying. Stale webhooks, terminating
# namespaces, and orphaned API services from a previous install can block pod
# creation and namespace deletion, causing silent deployment failures.

printf '\n%s══ Pre-flight checks ══════════════════════════════════════════════%s\n' "${_B}" "${_X}"

preflight_failed=false

# Bundle namespace list (deduplicated)
BUNDLE_NAMESPACES=$(echo "foo " | tr ' ' '\n' | sort -u | tr '\n' ' ')

# Check for terminating namespaces that overlap with our components
for ns in ${BUNDLE_NAMESPACES}; do
  phase=$(kubectl get ns "${ns}" -o jsonpath='{.status.phase}' 2>/dev/null || true)
  if [[ "${phase}" == "Terminating" ]]; then
    echo "ERROR: namespace '${ns}' is still terminating from a previous install."
    echo "  Wait for it to finish, or force-finalize with:"
    echo "    kubectl get ns ${ns} -o json | jq '.spec.finalizers=[]' | kubectl replace --raw /api/v1/namespaces/${ns}/finalize -f -"
    preflight_failed=true
  fi
done

# Check for stale webhooks whose backing services no longer exist.
# Scoped to bundle namespaces only to avoid false positives from unrelated
# platform webhooks in shared clusters.
if command -v jq &>/dev/null; then
  for kind in mutatingwebhookconfigurations validatingwebhookconfigurations; do
    while IFS=$'\t' read -r wh_name svc_ns svc_name; do
      # Only check webhooks pointing to our bundle namespaces
      is_bundle_ns=false
      for ns in ${BUNDLE_NAMESPACES}; do
        [[ "${svc_ns}" == "${ns}" ]] && is_bundle_ns=true && break
      done
      [[ "${is_bundle_ns}" == "false" ]] && continue

      # Use explicit NotFound check to avoid false positives from transient errors
      svc_check=$(kubectl get svc "${svc_name}" -n "${svc_ns}" 2>&1) || true
      if echo "${svc_check}" | grep -q "NotFound\|not found"; then
        echo "ERROR: ${kind} '${wh_name}' references non-existent service ${svc_ns}/${svc_name}."
        echo "  This will block pod/resource creation. Delete with: kubectl delete ${kind} ${wh_name}"
        preflight_failed=true
      fi
    done < <(kubectl get "${kind}" -o json 2>/dev/null | \
      jq -r '.items[] | .metadata.name as $wh | .webhooks[]? | select(.clientConfig.service != null) | [$wh, .clientConfig.service.namespace, .clientConfig.service.name] | @tsv' 2>/dev/null || true)
  done
else
  echo "NOTE: jq not found — skipping webhook pre-flight checks. Install jq for full pre-flight validation."
fi

# Check for stale API services (e.g., custom.metrics.k8s.io from prometheus-adapter)
if command -v jq &>/dev/null; then
  for api_svc in $(kubectl get apiservices -o json 2>/dev/null | jq -r '.items[] | select(.status.conditions[]? | .type == "Available" and .status == "False") | .metadata.name' 2>/dev/null || true); do
    echo "WARNING: API service '${api_svc}' is unavailable. This can block namespace deletion."
    echo "  Delete with: kubectl delete apiservice ${api_svc}"
    # API service issues are warnings, not hard failures — they don't block deployment directly
  done
else
  echo "NOTE: jq not found — skipping API service pre-flight checks."
fi

# Check for orphaned CRDs from previous deployments.
# Scoped to CRD groups belonging to components in this bundle to avoid
# false positives from unrelated platform installs on shared clusters.
ORPHANED_CRD_GROUPS=""
for group in ${ORPHANED_CRD_GROUPS}; do
  orphaned=$(kubectl get crd -o name 2>/dev/null | grep "\.${group}$" || true)
  if [[ -n "${orphaned}" ]]; then
    echo "WARNING: orphaned CRDs from previous deployment: ${orphaned}"
    echo "  These may cause conflicts. Delete with: kubectl delete ${orphaned}"
  fi
done

# Check for stale nodewright node taints from a previous deployment.
# Only remove taints if nodewright-operator is NOT already running (i.e., fresh deploy).
# If the operator is running, taints are legitimate scheduling guards.

if [[ "${preflight_failed}" == "true" ]]; then
  echo ""
  _fail "Pre-flight checks failed. Fix the issues above before deploying."
  echo "  To clean up partial state, run 'helm uninstall <release> -n <namespace>' for each affected component, then retry."
  exit 1
fi

_ok "Pre-flight checks passed"
printf '\n%s══ Deploying AICR components ══════════════════════════════════════%s\n' "${_B}" "${_X}"

# ==============================================================================
# Install loop
# ==============================================================================
# Generic install loop. Each folder's install.sh is rendered by localformat
# with the right helm command baked in — deploy.sh has no per-component
# knowledge here. Per-component special-case logic (async wait, DRA plugin
# restart) runs in the post-install blocks below, matched by component name.
cd "${HELM_WORKDIR}"

# Pre-count folders for accurate [N/M] progress display.
TOTAL_STEPS=0
for _d in "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/; do
  [[ -d "${_d}" ]] && TOTAL_STEPS=$((TOTAL_STEPS+1))
done

STEP=0

for dir in "${SCRIPT_DIR}"/[0-9][0-9][0-9]-*/; do
  [[ -d "${dir}" ]] || continue
  dir="${dir%/}"
  base="${dir##*/}"
  name="${base#[0-9][0-9][0-9]-}"
  STEP=$((STEP+1))
  # Source the namespace from the folder's install.sh — not the folder
  # basename — because the helm release name and its target namespace can
  # differ (e.g. nodewright-operator → namespace skyhook; gpu-operator-post →
  # namespace gpu-operator). cleanup_helm_hooks and the kai diagnostics
  # both operate on the namespace.
  namespace=$(awk '{ for (i=1;i<NF;i++) if ($i=="--namespace") { print $(i+1); exit } }' "${dir}/install.sh")
  _step_header "${STEP}" "${TOTAL_STEPS}" "${name}" "${namespace}" "${dir}"
  # Derive wait args: global --wait/--no-wait behavior + per-component timeout.
  COMPONENT_HELM_TIMEOUT="${HELM_TIMEOUT}"
  COMPONENT_MAX_RETRIES="${MAX_RETRIES}"
  COMPONENT_WAIT_ARGS=""
  case "${name}" in
    kai-scheduler)
      COMPONENT_HELM_TIMEOUT="20m"
      COMPONENT_MAX_RETRIES="1"
      ;;
    *-readiness)
      # Readiness gate folders run the gate CLI as a post-install/post-upgrade
      # helm hook Job that polls component signals until they pass or the gate's
      # own --max-wait deadline elapses. Helm --wait blocks on hook completion
      # regardless of --wait-for-jobs, so only --timeout is needed here.
      # The gate owns the deadline; helm cannot wait indefinitely (--wait is
      # bounded by --timeout), so this --timeout is DERIVED by the bundler as
      # gate --max-wait + a buffer — large enough that helm never preempts the
      # gate, small enough to still surface a hung gate shortly after. The gate
      # is a correctness barrier, so it ignores --no-wait and pins its args:
      #   MAX_RETRIES=1    the gate owns its own poll/retry loop; re-running the
      #                    whole Job on a transient helm error only doubles wait.
      COMPONENT_HELM_TIMEOUT="1h35m0s"
      COMPONENT_MAX_RETRIES="1"
      COMPONENT_WAIT_ARGS="--wait --timeout ${COMPONENT_HELM_TIMEOUT}"
      ;;
  esac
  # Components that didn't pin their own wait args above honor the global
  # --wait/--no-wait flag plus the async-component override.
  if [[ -z "${COMPONENT_WAIT_ARGS}" ]]; then
    if [[ "${NO_WAIT}" == "true" ]]; then
      COMPONENT_WAIT_ARGS="--timeout ${COMPONENT_HELM_TIMEOUT}"
    else
      COMPONENT_WAIT_ARGS="--wait --timeout ${COMPONENT_HELM_TIMEOUT}"
    fi
    if echo "${ASYNC_COMPONENTS}" | grep -qw "${name}"; then
      # Skip --wait (no readiness check) but keep --timeout for hook completion.
      COMPONENT_WAIT_ARGS="--timeout ${COMPONENT_HELM_TIMEOUT}"
      printf '%s│%s  (async component — skipping --wait, keeping --timeout for hooks)\n' "${_D}" "${_X}"
    fi
  fi
  export COMPONENT_WAIT_ARGS

  # Invoke the per-folder install.sh with retry. On failure, dump kai-scheduler
  # diagnostics and clean up stale Helm hook Jobs between attempts.
  attempt=0
  while true; do
    if ( cd "${dir}" && bash install.sh ); then
      _step_ok "${name}"
      break
    fi

    attempt=$((attempt + 1))
    dump_kai_scheduler_helm_diagnostics "${namespace}"

    if [[ ${attempt} -gt ${COMPONENT_MAX_RETRIES} ]]; then
      _step_fail "${name}" "${attempt}"
      helm_failed "${name}"
      break
    fi

    cleanup_helm_hooks "${namespace}"

    wait_secs=$(backoff_seconds "${attempt}")

    _step_retry "${name}" "${attempt}" "${COMPONENT_MAX_RETRIES}" "${wait_secs}"

    sleep "${wait_secs}"
  done

  # --- post-install name-matched blocks ---
done

if [[ -n "${FAILED_COMPONENTS}" ]]; then
  _fail "Deployment completed with failures (--best-effort):${FAILED_COMPONENTS}"
else
  _ok "All components installed successfully."
fi
echo
echo "NOTE: The above status reflects Helm install and manifest apply results,"
echo "not whether the cluster is ready for GPU workloads. On fresh"
echo "GPU nodes, cluster convergence may continue asynchronously after this"
echo "script exits. Full workload readiness can take additional time for:"
echo "  - node tuning (e.g., Nodewright, ~10-20 min on fresh nodes)"
echo "  - GPU operator operand rollout (driver, toolkit, device-plugin DS)"
echo "  - NVIDIA DRA kubelet plugin registration"
echo
echo "See: https://github.com/NVIDIA/aicr/blob/main/docs/user/cli-reference.md#deploy-script-behavior-deploysh"
