// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package terraform

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/NVIDIA/aicr/pkg/bundler/deployer"
	"github.com/NVIDIA/aicr/pkg/bundler/deployer/localformat"
	"github.com/NVIDIA/aicr/pkg/errors"
)

// bundleData is the render input shared by every generated file. One struct
// for all of them because the headers, the provider block and the module
// bodies must agree about the same three facts (version, rollover, serial),
// and threading them separately is how they stop agreeing.
type bundleData struct {
	Version         string
	Criteria        string
	ClusterRollover bool
	ChildModule     bool
	Serial          bool
	Components      []componentData

	// ReleaseMap is the releases output's body: every Helm release the bundle
	// installs, auxiliary ones included, as quoted name -> quoted namespace.
	// ComponentMap is the same for components only.
	ReleaseMap   []attr
	ComponentMap []attr
}

// Argument names this package emits in more than one place.
const (
	argWait    = "wait"
	argTimeout = "timeout"
)

// attr is one `name = expression` line. Value is already a rendered HCL
// expression — quoted, interpolated, or a bare literal — because the caller
// is the only place that knows which.
type attr struct {
	Name  string
	Value string
}

// componentData is one module call. The arguments arrive pre-grouped rather
// than as loose fields because the groups ARE the formatting: `terraform fmt`
// aligns the `=` of contiguous argument lines and resets at each blank line,
// so a generator that does not know its own groups cannot emit output that is
// already fmt-clean. See align.
type componentData struct {
	Label string
	Title string
	// Extra names the auxiliary folders, when there are any. Empty for the
	// common single-folder component.
	Extra string
	// Name and Namespace are also carried raw, for outputs.tf and the README,
	// where they are prose rather than arguments.
	Name      string
	Namespace string

	Identity    []attr // release_name, namespace, create_namespace
	Chart       []attr // chart, and the upstream coordinates when there are any
	ValuesFiles []string
	Phases      []attr // pre_chart / post_chart / readiness_chart, when present
	Behavior    []attr // atomic, wait, timeout, and the rollover trigger
	DependsOn   []string
	// Note is an inline comment above the behavior group, explaining a
	// per-component override. Empty when the component takes the defaults.
	Note string
}

// align renders a group of arguments as `terraform fmt` would: one line each,
// at the given indent, with the `=` of every line in the group padded to the
// same column.
//
// Emitting already-formatted HCL is not cosmetic. A bundle whose committed
// bytes differ from its generated bytes cannot be regenerated and diffed to
// prove it is current, which is the whole point of a generated bundle.
//
// Padding is computed over the argument NAMES, which are ASCII identifiers,
// so a byte count is the column count.
func align(indent string, attrs []attr) string {
	width := 0
	for _, a := range attrs {
		if len(a.Name) > width {
			width = len(a.Name)
		}
	}
	lines := make([]string, 0, len(attrs))
	for _, a := range attrs {
		lines = append(lines, fmt.Sprintf("%s%-*s = %s", indent, width, a.Name, a.Value))
	}
	return strings.Join(lines, "\n")
}

func (g *Generator) bundleData(components []component) bundleData {
	criteria := ""
	if g.RecipeResult.Criteria != nil {
		criteria = g.RecipeResult.Criteria.String()
	}
	data := bundleData{
		Version:         g.Version,
		Criteria:        criteria,
		ClusterRollover: g.ClusterRollover,
		ChildModule:     g.ChildModule,
		Serial:          g.Serial,
		Components:      make([]componentData, 0, len(components)),
	}
	for _, c := range components {
		primary := c.Primary
		cd := componentData{
			Label:     c.Label,
			Title:     componentTitle(c),
			Extra:     extraFolders(c),
			Name:      c.Name,
			Namespace: primary.Namespace,
			Identity: []attr{
				{"release_name", hclString(c.Name)},
				{"namespace", hclString(primary.Namespace)},
				{"create_namespace", strconv.FormatBool(headFolder(c).CreateNamespace)},
			},
			Chart:       chartAttrs(primary),
			ValuesFiles: valuesFilesFor(primary, g.DynamicValues[c.Name]),
			Phases:      phaseAttrs(c),
			Behavior: []attr{
				{"atomic", "var.atomic"},
				{argWait, "var.wait"},
				{argTimeout, "var.timeout"},
			},
			DependsOn: c.DependsOn,
		}
		// Per-component overrides are facts about the component, not knobs, so
		// they render as literals: an operator flipping var.wait for the bundle
		// must not silently re-enable a wait that is known to time out. The
		// readiness slot ignores var.wait entirely, so an async component
		// cannot disarm its own gate. deploy.sh and helmfile share the table.
		if ov, hasOverride := deployer.ComponentOverrideFor(c.Name); hasOverride {
			cd.Behavior = overrideBehavior(cd.Behavior, ov)
			cd.Note = overrideNote(ov)
		}
		if g.ClusterRollover {
			// The endpoint comes from a different variable in each mode: a
			// root module already has cluster_host for its own provider
			// config, while a child module has no connection variables at
			// all and takes cluster_endpoint purely for the shim.
			endpoint := "var.cluster_host"
			if g.ChildModule {
				endpoint = "var.cluster_endpoint"
			}
			cd.Behavior = append(cd.Behavior, attr{"cluster_endpoint", endpoint})
		}
		data.Components = append(data.Components, cd)
		data.ComponentMap = append(data.ComponentMap, attr{hclString(c.Name), hclString(primary.Namespace)})
		for _, f := range c.Folders() {
			data.ReleaseMap = append(data.ReleaseMap, attr{hclString(f.Name), hclString(f.Namespace)})
		}
	}
	return data
}

// headFolder is the first folder the component applies — the pre wrapper when
// there is one. Only the head creates the namespace; by the time a later slot
// runs it exists, and Helm 3 refuses to adopt a namespace another release
// created out-of-band.
func headFolder(c component) localformat.Folder {
	if c.Pre != nil {
		return *c.Pre
	}
	return c.Primary
}

// chartAttrs renders the chart coordinates: upstream name/repo/version, or a
// path to the chart directory localformat wrote into the bundle.
func chartAttrs(f localformat.Folder) []attr {
	if f.Kind != localformat.KindUpstreamHelm || f.Upstream == nil {
		return []attr{{"chart", localChartExpr(f.Dir)}}
	}
	out := []attr{{"chart", hclString(f.Upstream.Chart)}}
	if f.Upstream.Repo != "" {
		out = append(out, attr{"repository", hclString(f.Upstream.Repo)})
	}
	if f.Upstream.Version != "" {
		out = append(out, attr{"chart_version", hclString(f.Upstream.Version)})
	}
	return out
}

// phaseAttrs renders the auxiliary slots the component actually has. An absent
// slot is left unset so the module's count guard drops the resource.
func phaseAttrs(c component) []attr {
	var out []attr
	if c.Pre != nil {
		out = append(out, attr{"pre_chart", localChartExpr(c.Pre.Dir)})
	}
	if c.Post != nil {
		out = append(out, attr{"post_chart", localChartExpr(c.Post.Dir)})
	}
	if c.Readiness != nil {
		out = append(out, attr{"readiness_chart", localChartExpr(c.Readiness.Dir)})
	}
	return out
}

// overrideBehavior replaces the defaulted behavior arguments with the
// component's own values.
func overrideBehavior(base []attr, ov deployer.ComponentOverride) []attr {
	out := make([]attr, 0, len(base))
	for _, a := range base {
		switch a.Name {
		case argWait:
			out = append(out, attr{argWait, strconv.FormatBool(ov.Wait)})
		case argTimeout:
			if ov.TimeoutSeconds > 0 {
				out = append(out, attr{argTimeout, strconv.Itoa(ov.TimeoutSeconds)})
				continue
			}
			out = append(out, a)
		default:
			out = append(out, a)
		}
	}
	return out
}

// overrideNote explains an override at its call site. A generated argument
// that silently contradicts the bundle-wide variable reads as a bug.
func overrideNote(ov deployer.ComponentOverride) string {
	if !ov.Wait {
		return "Asynchronous: helm --wait times out on this component's custom-resource\n  # readiness even though its pods start. Ordering still holds; readiness does not."
	}
	return "Per-component override."
}

// componentTitle is the comment above a module call: the chart folder and what
// is in it, so a reader of main.tf need not open the directory.
func componentTitle(c component) string {
	f := c.Primary
	u := f.Upstream
	switch {
	case f.Kind == localformat.KindUpstreamHelm && u != nil && u.Version != "":
		return fmt.Sprintf("%s — %s %s", f.Dir, u.Chart, u.Version)
	case f.Kind == localformat.KindUpstreamHelm && u != nil:
		return fmt.Sprintf("%s — %s", f.Dir, u.Chart)
	default:
		return fmt.Sprintf("%s — chart bundled in this directory", f.Dir)
	}
}

// extraFolders names the auxiliary folders this call also installs. They are a
// second line rather than part of the title: most components have none, and the
// chart is what a reader is looking for.
func extraFolders(c component) string {
	var dirs []string
	for _, f := range c.Folders() {
		if f.Dir != c.Primary.Dir {
			dirs = append(dirs, f.Dir)
		}
	}
	return strings.Join(dirs, ", ")
}

// generatedFile pairs a template with the path it renders to, relative to the
// bundle root.
type generatedFile struct {
	path string
	tmpl string
}

// writeTerraform renders the .tf layer over the folders localformat already
// wrote. Every file is rendered from the same bundleData.
func (g *Generator) writeTerraform(outputDir string, data bundleData, output *deployer.Output) error {
	files := []generatedFile{
		{fileMain, mainTemplate},
		{fileVersions, versionsTemplate},
		{fileVars, variablesTemplate},
		{fileOutputs, outputsTemplate},
		{fileReadme, readmeTemplate},
		{filepath.Join(moduleDir, "main.tf"), moduleMainTemplate},
		{filepath.Join(moduleDir, "variables.tf"), moduleVariablesTemplate},
		{filepath.Join(moduleDir, "outputs.tf"), moduleOutputsTemplate},
	}
	// terraform.tfvars.example is a root-module artifact: a child module is
	// configured by its caller's module block, not by a tfvars file.
	if !g.ChildModule {
		files = append(files, generatedFile{fileTfvars, tfvarsTemplate})
	}

	for _, gf := range files {
		abs, err := deployer.SafeJoin(outputDir, gf.path)
		if err != nil {
			return err
		}
		if mkErr := os.MkdirAll(filepath.Dir(abs), 0o755); mkErr != nil {
			return errors.Wrap(errors.ErrCodeInternal,
				fmt.Sprintf("failed to create directory for %s", gf.path), mkErr)
		}
		rendered, renderErr := renderTemplate(gf.path, gf.tmpl, data)
		if renderErr != nil {
			return renderErr
		}
		if writeErr := os.WriteFile(abs, rendered, 0o600); writeErr != nil {
			return errors.Wrap(errors.ErrCodeInternal,
				fmt.Sprintf("failed to write %s", gf.path), writeErr)
		}
		output.Files = append(output.Files, abs)
		output.TotalSize += int64(len(rendered))
	}
	return nil
}

// templateFuncs are the helpers the bundle templates may call. Kept to the
// minimum that cannot be precomputed in bundleData: quoting has to happen at
// the point of emission because the same value is also used unquoted in
// README prose.
var templateFuncs = template.FuncMap{
	"quote": hclString,
	"align": align,
}

func renderTemplate(name, text string, data bundleData) ([]byte, error) {
	tmpl, err := template.New(name).Funcs(templateFuncs).Parse(text)
	if err != nil {
		return nil, errors.Wrap(errors.ErrCodeInternal,
			fmt.Sprintf("failed to parse template %s", name), err)
	}
	var buf strings.Builder
	if execErr := tmpl.Execute(&buf, data); execErr != nil {
		return nil, errors.Wrap(errors.ErrCodeInternal,
			fmt.Sprintf("failed to render %s", name), execErr)
	}
	return []byte(buf.String()), nil
}
