// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package terraform

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/NVIDIA/aicr/pkg/bundler/deployer"
	"github.com/NVIDIA/aicr/pkg/bundler/deployer/localformat"
	"github.com/NVIDIA/aicr/pkg/errors"
)

// bundleData is the render input shared by every generated file. One struct
// for all of them because the headers, the provider block and the module
// bodies must agree about the same three facts (version, rollover, serial),
// and threading them separately is how they stop agreeing.
type bundleData struct {
	Version         string
	Criteria        string
	ClusterRollover bool
	ChildModule     bool
	Serial          bool
	Releases        []releaseData

	// ReleaseMap is the releases output's body: quoted release name -> quoted
	// namespace, aligned like any other argument group.
	ReleaseMap []attr
}

// Argument names this package emits in more than one place.
const (
	argWait    = "wait"
	argTimeout = "timeout"
)

// attr is one `name = expression` line. Value is already a rendered HCL
// expression — quoted, interpolated, or a bare literal — because the caller
// is the only place that knows which.
type attr struct {
	Name  string
	Value string
}

// releaseData is one module call. The arguments arrive pre-grouped rather
// than as loose fields because the groups ARE the formatting: `terraform fmt`
// aligns the `=` of contiguous argument lines and resets at each blank line,
// so a generator that does not know its own groups cannot emit output that is
// already fmt-clean. See align.
type releaseData struct {
	Label string
	Title string
	// ReleaseName and Namespace are also carried raw, for outputs.tf and the
	// README, where they are prose rather than arguments.
	ReleaseName string
	Namespace   string

	Identity    []attr // release_name, namespace, create_namespace
	Chart       []attr // chart, and the upstream coordinates when there are any
	Behavior    []attr // atomic, wait, timeout, and the rollover trigger
	ValuesFiles []string
	DependsOn   []string
	// Note is an inline comment above the behavior group, explaining a
	// per-component override. Empty when the component takes the defaults.
	Note string
}

// align renders a group of arguments as `terraform fmt` would: one line each,
// at the given indent, with the `=` of every line in the group padded to the
// same column.
//
// Emitting already-formatted HCL is not cosmetic. A bundle whose committed
// bytes differ from its generated bytes cannot be regenerated and diffed to
// prove it is current, which is the whole point of a generated bundle.
//
// Padding is computed over the argument NAMES, which are ASCII identifiers,
// so a byte count is the column count.
func align(indent string, attrs []attr) string {
	width := 0
	for _, a := range attrs {
		if len(a.Name) > width {
			width = len(a.Name)
		}
	}
	lines := make([]string, 0, len(attrs))
	for _, a := range attrs {
		lines = append(lines, fmt.Sprintf("%s%-*s = %s", indent, width, a.Name, a.Value))
	}
	return strings.Join(lines, "\n")
}

func (g *Generator) bundleData(releases []release) bundleData {
	criteria := ""
	if g.RecipeResult.Criteria != nil {
		criteria = g.RecipeResult.Criteria.String()
	}
	data := bundleData{
		Version:         g.Version,
		Criteria:        criteria,
		ClusterRollover: g.ClusterRollover,
		ChildModule:     g.ChildModule,
		Serial:          g.Serial,
		Releases:        make([]releaseData, 0, len(releases)),
	}
	for _, r := range releases {
		f := r.Folder
		rd := releaseData{
			Label:       r.Label,
			Title:       folderTitle(f),
			ReleaseName: f.Name,
			Namespace:   f.Namespace,
			Identity: []attr{
				{"release_name", hclString(f.Name)},
				{"namespace", hclString(f.Namespace)},
				{"create_namespace", strconv.FormatBool(f.CreateNamespace)},
			},
			Behavior: []attr{
				{"atomic", "var.atomic"},
				{argWait, "var.wait"},
				{argTimeout, "var.timeout"},
			},
			ValuesFiles: valuesFilesForFolder(f, g.DynamicValues[f.Parent]),
			DependsOn:   r.DependsOn,
		}
		if f.Kind == localformat.KindUpstreamHelm && f.Upstream != nil {
			rd.Chart = []attr{{"chart", hclString(f.Upstream.Chart)}}
			if f.Upstream.Repo != "" {
				rd.Chart = append(rd.Chart, attr{"repository", hclString(f.Upstream.Repo)})
			}
			if f.Upstream.Version != "" {
				rd.Chart = append(rd.Chart, attr{"chart_version", hclString(f.Upstream.Version)})
			}
		} else {
			rd.Chart = []attr{{"chart", localChartExpr(f.Dir)}}
		}
		// Per-component overrides, keyed by the PARENT component so a
		// primary release and its injected folders agree. Rendered as
		// literals rather than var references: they are facts about the
		// component, not knobs, and an operator who flips var.wait for the
		// bundle must not silently re-enable a wait that is known to time
		// out. deploy.sh and the helmfile deployer make the same override.
		if ov, hasOverride := deployer.ComponentOverrideFor(f.Parent); hasOverride {
			rd.Behavior = overrideBehavior(rd.Behavior, ov)
			rd.Note = overrideNote(ov)
		}
		if g.ClusterRollover {
			// The endpoint comes from a different variable in each mode: a
			// root module already has cluster_host for its own provider
			// config, while a child module has no connection variables at
			// all and takes cluster_endpoint purely for the shim.
			endpoint := "var.cluster_host"
			if g.ChildModule {
				endpoint = "var.cluster_endpoint"
			}
			rd.Behavior = append(rd.Behavior, attr{"cluster_endpoint", endpoint})
		}
		data.Releases = append(data.Releases, rd)
		data.ReleaseMap = append(data.ReleaseMap, attr{hclString(f.Name), hclString(f.Namespace)})
	}
	return data
}

// overrideBehavior replaces the defaulted behavior arguments with the
// component's own values.
func overrideBehavior(base []attr, ov deployer.ComponentOverride) []attr {
	out := make([]attr, 0, len(base))
	for _, a := range base {
		switch a.Name {
		case argWait:
			out = append(out, attr{argWait, strconv.FormatBool(ov.Wait)})
		case argTimeout:
			if ov.TimeoutSeconds > 0 {
				out = append(out, attr{argTimeout, strconv.Itoa(ov.TimeoutSeconds)})
				continue
			}
			out = append(out, a)
		default:
			out = append(out, a)
		}
	}
	return out
}

// overrideNote explains an override at its call site. A generated argument
// that silently contradicts the bundle-wide variable is the kind of thing a
// reader assumes is a bug.
func overrideNote(ov deployer.ComponentOverride) string {
	if !ov.Wait {
		return "Asynchronous: helm --wait times out on this component's custom-resource\n  # readiness even though its pods start. Ordering still holds; readiness does not."
	}
	return "Per-component override."
}

// folderTitle is the comment above a module call: enough for a reader of
// main.tf to know what the release is without opening its folder.
func folderTitle(f localformat.Folder) string {
	switch {
	case f.Kind == localformat.KindUpstreamHelm && f.Upstream != nil && f.Upstream.Version != "":
		return fmt.Sprintf("%s — %s %s", f.Dir, f.Upstream.Chart, f.Upstream.Version)
	case f.Kind == localformat.KindUpstreamHelm && f.Upstream != nil:
		return fmt.Sprintf("%s — %s", f.Dir, f.Upstream.Chart)
	default:
		return fmt.Sprintf("%s — chart bundled in this directory", f.Dir)
	}
}

// generatedFile pairs a template with the path it renders to, relative to the
// bundle root.
type generatedFile struct {
	path string
	tmpl string
}

// writeTerraform renders the .tf layer over the folders localformat already
// wrote. Every file is rendered from the same bundleData.
func (g *Generator) writeTerraform(outputDir string, data bundleData, output *deployer.Output) error {
	files := []generatedFile{
		{fileMain, mainTemplate},
		{fileVersions, versionsTemplate},
		{fileVars, variablesTemplate},
		{fileOutputs, outputsTemplate},
		{fileReadme, readmeTemplate},
		{filepath.Join(moduleDir, "main.tf"), moduleMainTemplate},
		{filepath.Join(moduleDir, "variables.tf"), moduleVariablesTemplate},
		{filepath.Join(moduleDir, "outputs.tf"), moduleOutputsTemplate},
	}
	// terraform.tfvars.example is a root-module artifact: a child module is
	// configured by its caller's module block, not by a tfvars file.
	if !g.ChildModule {
		files = append(files, generatedFile{fileTfvars, tfvarsTemplate})
	}

	for _, gf := range files {
		abs, err := deployer.SafeJoin(outputDir, gf.path)
		if err != nil {
			return err
		}
		if mkErr := os.MkdirAll(filepath.Dir(abs), 0o755); mkErr != nil {
			return errors.Wrap(errors.ErrCodeInternal,
				fmt.Sprintf("failed to create directory for %s", gf.path), mkErr)
		}
		rendered, renderErr := renderTemplate(gf.path, gf.tmpl, data)
		if renderErr != nil {
			return renderErr
		}
		if writeErr := os.WriteFile(abs, rendered, 0o600); writeErr != nil {
			return errors.Wrap(errors.ErrCodeInternal,
				fmt.Sprintf("failed to write %s", gf.path), writeErr)
		}
		output.Files = append(output.Files, abs)
		output.TotalSize += int64(len(rendered))
	}
	return nil
}

// templateFuncs are the helpers the bundle templates may call. Kept to the
// minimum that cannot be precomputed in bundleData: quoting has to happen at
// the point of emission because the same value is also used unquoted in
// README prose.
var templateFuncs = template.FuncMap{
	"quote": hclString,
	"align": align,
}

func renderTemplate(name, text string, data bundleData) ([]byte, error) {
	tmpl, err := template.New(name).Funcs(templateFuncs).Parse(text)
	if err != nil {
		return nil, errors.Wrap(errors.ErrCodeInternal,
			fmt.Sprintf("failed to parse template %s", name), err)
	}
	var buf strings.Builder
	if execErr := tmpl.Execute(&buf, data); execErr != nil {
		return nil, errors.Wrap(errors.ErrCodeInternal,
			fmt.Sprintf("failed to render %s", name), execErr)
	}
	return []byte(buf.String()), nil
}
