# Generated by AICR v1.0.0 — do not edit.
#
# One module call per component. depends_on carries the recipe's graph exactly:
# a component waits for its declared dependencies and nothing else, so
# independent components apply concurrently. A component's own pre / post /
# readiness folders chain inside the module, which is why depending on the
# module means the component is done.

# 001-nfd — node-feature-discovery 0.18.1
module "nfd" {
  source = "./modules/component"

  release_name     = "nfd"
  namespace        = "node-feature-discovery"
  create_namespace = true

  chart         = "node-feature-discovery"
  repository    = "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart_version = "0.18.1"

  values_files = [
    "${path.module}/001-nfd/values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}

# 002-gpu-operator — gpu-operator v25.3.3
# plus 003-gpu-operator-readiness
module "gpu_operator" {
  source = "./modules/component"

  release_name     = "gpu-operator"
  namespace        = "gpu-operator"
  create_namespace = true

  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v25.3.3"

  values_files = [
    "${path.module}/002-gpu-operator/values.yaml",
  ]

  readiness_chart = "${path.module}/003-gpu-operator-readiness"

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout

  depends_on = [
    module.nfd,
  ]
}
