# Generated by AICR v1.0.0 — do not edit.
#
# One AICR component, as one Helm release. Every module call in ../../main.tf
# shares this module; the component's identity lives entirely in the arguments
# and in the values files it is handed.
#
# The ordering edges are on the module CALLS, not on the resource in here. A
# depends_on on a call is a fact about everything the module contains, so the
# recipe's graph keeps holding if this module ever grows a second resource.

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
  }
}

resource "helm_release" "this" {
  name             = var.release_name
  namespace        = var.namespace
  create_namespace = var.create_namespace

  chart      = var.chart
  repository = var.repository
  version    = var.chart_version

  values = [for f in var.values_files : file(f)]

  # wait gates the resource on the release's workloads, which is what turns an
  # ordering edge into a readiness edge. It does NOT wait on custom-resource
  # status: a component whose real signal is a CR condition still needs its
  # own gate. See README.md.
  wait          = var.wait
  wait_for_jobs = var.wait
  timeout       = var.timeout
  atomic        = var.atomic

  # Escape hatch, off by default like the provider's own. A component whose
  # manifests reference CRDs that a PRIOR release installs can fail dry-run
  # validation against a cluster that has not registered them yet; turning
  # this on for the whole bundle is the blunt fix, and narrowing wait/ordering
  # is the better one.
  disable_openapi_validation = var.disable_openapi_validation
}
