# Generated by AICR v1.0.0 — do not edit.
#
# One module call per release. depends_on carries the recipe's dependency
# graph exactly: a component waits for its declared dependencies and nothing
# else, so independent components apply concurrently.

# 001-cert-manager — cert-manager v1.17.2
module "cert_manager" {
  source = "./modules/component"

  release_name     = "cert-manager"
  namespace        = "cert-manager"
  create_namespace = true

  chart         = "cert-manager"
  repository    = "https://charts.jetstack.io"
  chart_version = "v1.17.2"

  values_files = [
    "${path.module}/001-cert-manager/values.yaml",
    "${path.module}/001-cert-manager/cluster-values.yaml",
  ]

  atomic  = var.atomic
  wait    = var.wait
  timeout = var.timeout
}
